services:
  back_medico:
    container_name: back_medico
    image: node-test:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT_APLICATION}:3001'
    links:
      - ddbb_mysql_medicos
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
    networks:
      - network_medico
    
  ddbb_mysql_medicos:
    image: mysql:latest
    container_name: ddbb_mysql_medicos
    environment:
      MYSQL_ROOT_PASSWORD: ${LABORATORY_DB_PASSWORD}
      MYSQL_DATABASE: ${LABORATORY_DB_DATABASE}
      MYSQL_USER: ${LABORATORY_DB_USERNAME}
    ports:
      - ${LABORATORY_DB_PORT}:3306
    volumes:
      - mysql_medico_data:/var/lib/mysql
    networks:
      - network_medico

volumes:
  mysql_medico_data: {}

networks:
  network_medico:
    driver: bridge